services:
  - type: web
    name: classroom-monitor
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://afreedhbaafreedhappi_db_user:Afreedh123@cluster0.zf3gpng.mongodb.net/classroom_monitoring?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: your_super_secret_jwt_key_2024
      - key: JWT_EXPIRE
        value: 7d